// All site copy and data, in both languages. Plain prose, no emoji, no dashes.

export const translations = {
  en: {
    nav: { about: "About", journey: "Route", work: "Work", apps: "Apps", papers: "Papers", contact: "Contact" },
    hero: {
      eyebrow: "DevOps Engineer · Germany",
      titleBefore: "I used to run hotel front desks. Now I keep ",
      titleAccent: "infrastructure",
      titleAfter: " running.",
      sub: "I build CI/CD pipelines, run Kubernetes clusters and write Terraform. Before that I spent twenty years keeping hotels and stores running, which turns out to be the same job with different tools: people count on you, and downtime is not an option.",
      viewWork: "View work",
      downloadCV: "Download CV",
      stamp: "Available for work",
    },
    about: {
      label: "About",
      title: "From the front desk to production",
      p1: "For over twenty years I managed places where things simply had to work: a Dixons store in Rhodes, then front desk operations at Sheraton hotels. When a guest arrives at two in the morning, nobody cares whose shift it was or which system failed. You fix it.",
      p2: "That is the mindset I bring to DevOps. I design CI/CD pipelines, orchestrate containers with Kubernetes, provision infrastructure with Terraform and monitor everything with Prometheus and Grafana. A cluster is just another operation that has to stay open.",
      p3: "I graduated from Ironhack's DevOps and Cloud Computing bootcamp in Germany, where my final project won the Hackshow: an AI assistant that answers hotel staff questions from the hotel's own documentation. The two halves of my career finally shook hands.",
      photoCaption: "April 2026. The moment the Hackshow winner was announced, photographed from my desk.",
      photoNote: "First place, Ironhack Hackshow",
      stats: [
        { value: "20+", label: "years in operations" },
        { value: "5+", label: "cloud projects" },
        { value: "2", label: "certifications" },
        { value: "DE", label: "based in Germany" },
      ],
    },
    journey: {
      label: "The route",
      title: "How I got here",
      steps: [
        { year: "2009", title: "Retail management", desc: "Store manager at Dixons in Rhodes. Teams, inventory, targets, and the July tourist rush." },
        { year: "2023", title: "Hotel operations", desc: "Front desk at international five-star hotels, including Sheraton. Round-the-clock operations where a failure walks up to the desk in person." },
        { year: "2025", title: "The pivot", desc: "Enrolled in Ironhack's DevOps and Cloud Computing bootcamp. Built real infrastructure from week one." },
        { year: "2026", title: "DevOps engineer", desc: "Azure, Kubernetes, Terraform, CI/CD. Won the Hackshow. Looking for the next operation to keep running." },
      ],
    },
    work: {
      label: "Selected work",
      note: "a running log",
      viewCode: "View code",
      liveDemo: "Live demo",
      award: "Hackshow winner",
      items: [
        {
          year: "2026",
          title: "Hotel Knowledge Assistant",
          awarded: true,
          desc: "An AI assistant that answers hotel staff questions from the hotel's own documentation. Retrieval-augmented generation on Azure with AI Search and OpenAI, a FastAPI backend, and the whole thing provisioned with Terraform.",
          tags: "Azure OpenAI, AI Search, FastAPI, Terraform, Docker",
          github: "https://github.com/Kabamaru2372/hotel-training-RAG-pipeline",
          demo: "/hotel-rag/",
          image: "/hotel-rag/thumbnail.png",
        },
        {
          year: "2026",
          title: "Expensy",
          desc: "A full-stack expense tracker on Azure AKS with a complete pipeline behind it: GitHub Actions for CI/CD, Prometheus and Grafana for monitoring, Kubernetes secrets, Redis caching.",
          tags: "Azure AKS, GitHub Actions, Kubernetes, Prometheus, Grafana, Redis, MongoDB",
          github: "https://github.com/Kabamaru2372/max.devops.expensy",
        },
        {
          year: "2025",
          title: "3-Tier Voting App",
          desc: "A multi-tier voting system built the way enterprises actually deploy: Terraform provisions it, Ansible configures it, Docker Compose runs it, GitHub Actions ships it.",
          tags: "Terraform, Ansible, Docker, GitHub Actions, PostgreSQL, Redis",
          github: "https://github.com/Kabamaru2372/3-tier-application",
        },
        {
          year: "2025",
          title: "W3 Combo",
          desc: "Infrastructure as code for a multi-service environment on AWS. Networking, resource management and repeatable deployments, all in Terraform.",
          tags: "Terraform, HCL, AWS, networking",
          github: "https://github.com/Kabamaru2372/w3-combo",
        },
        {
          year: "2026",
          title: "fotiospongas.dev",
          desc: "This site. React and Vite, deployed to GitHub Pages through GitHub Actions. Every push builds and ships automatically.",
          tags: "React, Vite, GitHub Actions, GitHub Pages",
          github: "https://github.com/Kabamaru2372/fotios.website",
        },
      ],
    },
    apps: {
      label: "After hours",
      title: "Apps I built because I wanted them to exist",
      intro: "DevOps is the day job. These started as questions I could not let go of.",
      picksy: {
        title: "Picksy: Be Present",
        desc: "An iOS app that counts how many times you pick up your phone, shows you the pattern, and helps you and your friends break it. Live on the App Store.",
        tags: "Swift, SwiftUI, Live Activities, WidgetKit, Supabase",
        appStore: "App Store",
        site: "getpicksy.app",
        appStoreUrl: "https://apps.apple.com/de/app/picksy-be-present/id6761116771",
        siteUrl: "https://getpicksy.app",
      },
      scytale: {
        title: "Scytale",
        desc: "A privacy-first messenger with no phone numbers, built on the decentralized Session network. Encrypted calls, voice masking, and nothing that identifies you.",
        tags: "Swift, WebRTC, CallKit, Xcode Cloud",
        link: "Learn more",
        linkUrl: "/scytale/",
      },
    },
    papers: {
      label: "The papers",
      title: "Credentials",
      flipHint: "Click to flip",
      items: [
        {
          title: "DevOps & Cloud Computing",
          issuer: "Ironhack",
          date: "March 2026",
          image: "/Screenshot 2026-03-10 at 01.01.28.png",
          facts: [
            "400 hours over 6 months, in Germany",
            "Docker and Kubernetes: images, orchestration, Helm charts",
            "Terraform and Ansible: provisioning and configuration as code",
            "AWS and Azure: compute, storage, networking, IAM",
            "CI/CD with GitHub Actions, from commit to production",
            "Final project, the Hotel Knowledge Assistant, won the cohort's Hackshow: first place out of every team",
          ],
        },
        {
          title: "AWS Cloud Practitioner Essentials",
          issuer: "AWS Training & Certification",
          date: "August 2025",
          image: "/Screenshot 2026-03-10 at 01.00.39.png",
          facts: [
            "Core AWS services and how they fit together",
            "IAM, security practices, the shared responsibility model",
            "Pricing, billing and cost optimization strategies",
            "EC2, S3, RDS and Lambda in practice",
            "The global AWS infrastructure: regions, availability zones, edge locations",
          ],
        },
      ],
    },
    skills: {
      label: "The toolkit",
      title: "Tools I work with",
      groups: [
        { name: "Cloud & infrastructure", items: "Azure, AWS, Terraform, Azure AKS, Azure AI Foundry, Blob Storage, Azure AI Search" },
        { name: "Containers & orchestration", items: "Docker, Kubernetes, Docker Compose, Helm" },
        { name: "CI/CD & automation", items: "GitHub Actions, Git, Ansible" },
        { name: "Monitoring & observability", items: "Prometheus, Grafana, alerting" },
        { name: "Development", items: "Python, Node.js, FastAPI, Next.js, Swift, Bash" },
        { name: "Databases & caching", items: "MongoDB, Redis, PostgreSQL" },
      ],
    },
    contact: {
      label: "Contact",
      title: "The desk is staffed",
      sub: "I am looking for DevOps and cloud engineering work in Germany. If you have systems that need to stay up, we should talk.",
      emailLabel: "Email",
      copied: "Copied",
      copyHint: "click to copy",
    },
    footer: { location: "Fotios Pongas · Germany" },
  },

  de: {
    nav: { about: "Über mich", journey: "Werdegang", work: "Arbeit", apps: "Apps", papers: "Zertifikate", contact: "Kontakt" },
    hero: {
      eyebrow: "DevOps Engineer · Deutschland",
      titleBefore: "Früher leitete ich Hotelrezeptionen. Heute halte ich ",
      titleAccent: "Infrastruktur",
      titleAfter: " am Laufen.",
      sub: "Ich baue CI/CD-Pipelines, betreibe Kubernetes-Cluster und schreibe Terraform. Davor habe ich zwanzig Jahre lang Hotels und Geschäfte am Laufen gehalten. Im Grunde derselbe Beruf mit anderen Werkzeugen: Menschen verlassen sich auf dich, und Ausfall ist keine Option.",
      viewWork: "Projekte ansehen",
      downloadCV: "CV herunterladen",
      stamp: "Offen für Angebote",
    },
    about: {
      label: "Über mich",
      title: "Von der Rezeption in die Produktion",
      p1: "Über zwanzig Jahre lang habe ich Orte geleitet, an denen alles funktionieren musste: ein Dixons-Geschäft auf Rhodos, danach den Empfang in Sheraton-Hotels. Wenn ein Gast um zwei Uhr nachts ankommt, interessiert niemanden, wessen Schicht es war oder welches System versagt hat. Man löst es.",
      p2: "Genau diese Haltung bringe ich ins DevOps-Engineering. Ich entwerfe CI/CD-Pipelines, orchestriere Container mit Kubernetes, provisioniere Infrastruktur mit Terraform und überwache alles mit Prometheus und Grafana. Ein Cluster ist am Ende auch nur ein Betrieb, der offen bleiben muss.",
      p3: "Das Ironhack-Bootcamp für DevOps und Cloud Computing habe ich in Deutschland abgeschlossen. Mein Abschlussprojekt, ein KI-Assistent für Hotelpersonal, gewann die Hackshow. Meine zwei Berufsleben haben sich endlich die Hand gegeben.",
      photoCaption: "April 2026. Der Moment der Siegerehrung, fotografiert von meinem Schreibtisch aus.",
      photoNote: "Erster Platz, Ironhack Hackshow",
      stats: [
        { value: "20+", label: "Jahre im operativen Betrieb" },
        { value: "5+", label: "Cloud-Projekte" },
        { value: "2", label: "Zertifizierungen" },
        { value: "DE", label: "wohnhaft in Deutschland" },
      ],
    },
    journey: {
      label: "Der Werdegang",
      title: "Wie ich hierher kam",
      steps: [
        { year: "2009", title: "Einzelhandel", desc: "Filialleiter bei Dixons auf Rhodos. Teams, Warenbestand, Umsatzziele und der Touristenansturm im Juli." },
        { year: "2023", title: "Hotellerie", desc: "Empfang in internationalen Fünf-Sterne-Hotels, darunter Sheraton. Betrieb rund um die Uhr, wo ein Ausfall persönlich am Tresen erscheint." },
        { year: "2025", title: "Der Wechsel", desc: "Ironhack-Bootcamp für DevOps und Cloud Computing. Echte Infrastruktur ab der ersten Woche." },
        { year: "2026", title: "DevOps Engineer", desc: "Azure, Kubernetes, Terraform, CI/CD. Hackshow gewonnen. Auf der Suche nach dem nächsten Betrieb, der laufen muss." },
      ],
    },
    work: {
      label: "Ausgewählte Arbeiten",
      note: "ein laufendes Protokoll",
      viewCode: "Code ansehen",
      liveDemo: "Live-Demo",
      award: "Hackshow-Gewinner",
      items: [
        {
          year: "2026",
          title: "Hotel Knowledge Assistant",
          awarded: true,
          desc: "Ein KI-Assistent, der Fragen des Hotelpersonals aus der hoteleigenen Dokumentation beantwortet. Retrieval-Augmented Generation auf Azure mit AI Search und OpenAI, FastAPI-Backend, vollständig mit Terraform provisioniert.",
          tags: "Azure OpenAI, AI Search, FastAPI, Terraform, Docker",
          github: "https://github.com/Kabamaru2372/hotel-training-RAG-pipeline",
          demo: "/hotel-rag/",
          image: "/hotel-rag/thumbnail.png",
        },
        {
          year: "2026",
          title: "Expensy",
          desc: "Ein Full-Stack-Ausgabentracker auf Azure AKS mit kompletter Pipeline dahinter: GitHub Actions für CI/CD, Prometheus und Grafana fürs Monitoring, Kubernetes Secrets, Redis-Caching.",
          tags: "Azure AKS, GitHub Actions, Kubernetes, Prometheus, Grafana, Redis, MongoDB",
          github: "https://github.com/Kabamaru2372/max.devops.expensy",
        },
        {
          year: "2025",
          title: "3-Tier Voting App",
          desc: "Ein mehrschichtiges Abstimmungssystem, aufgebaut wie in echten Unternehmen: Terraform provisioniert, Ansible konfiguriert, Docker Compose betreibt, GitHub Actions liefert aus.",
          tags: "Terraform, Ansible, Docker, GitHub Actions, PostgreSQL, Redis",
          github: "https://github.com/Kabamaru2372/3-tier-application",
        },
        {
          year: "2025",
          title: "W3 Combo",
          desc: "Infrastructure as Code für eine Multi-Service-Umgebung auf AWS. Netzwerk, Ressourcenverwaltung und wiederholbare Deployments, alles in Terraform.",
          tags: "Terraform, HCL, AWS, Networking",
          github: "https://github.com/Kabamaru2372/w3-combo",
        },
        {
          year: "2026",
          title: "fotiospongas.dev",
          desc: "Diese Seite. React und Vite, ausgeliefert über GitHub Pages mit GitHub Actions. Jeder Push baut und veröffentlicht automatisch.",
          tags: "React, Vite, GitHub Actions, GitHub Pages",
          github: "https://github.com/Kabamaru2372/fotios.website",
        },
      ],
    },
    apps: {
      label: "Nach Feierabend",
      title: "Apps, die ich gebaut habe, weil ich sie haben wollte",
      intro: "DevOps ist der Beruf. Diese hier begannen als Fragen, die mich nicht losließen.",
      picksy: {
        title: "Picksy: Be Present",
        desc: "Eine iOS-App, die zählt, wie oft man zum Handy greift, das Muster sichtbar macht und dabei hilft, es gemeinsam mit Freunden zu durchbrechen. Live im App Store.",
        tags: "Swift, SwiftUI, Live Activities, WidgetKit, Supabase",
        appStore: "App Store",
        site: "getpicksy.app",
        appStoreUrl: "https://apps.apple.com/de/app/picksy-be-present/id6761116771",
        siteUrl: "https://getpicksy.app",
      },
      scytale: {
        title: "Scytale",
        desc: "Ein Messenger mit Privatsphäre als Ausgangspunkt: keine Telefonnummern, aufgebaut auf dem dezentralen Session-Netzwerk. Verschlüsselte Anrufe, Stimmverfremdung, und nichts, was dich identifiziert.",
        tags: "Swift, WebRTC, CallKit, Xcode Cloud",
        link: "Mehr erfahren",
        linkUrl: "/scytale/",
      },
    },
    papers: {
      label: "Die Papiere",
      title: "Abschlüsse",
      flipHint: "Klicken zum Umdrehen",
      items: [
        {
          title: "DevOps & Cloud Computing",
          issuer: "Ironhack",
          date: "März 2026",
          image: "/Screenshot 2026-03-10 at 01.01.28.png",
          facts: [
            "400 Stunden über 6 Monate, in Deutschland",
            "Docker und Kubernetes: Images, Orchestrierung, Helm Charts",
            "Terraform und Ansible: Provisionierung und Konfiguration als Code",
            "AWS und Azure: Compute, Storage, Networking, IAM",
            "CI/CD mit GitHub Actions, vom Commit bis zur Produktion",
            "Abschlussprojekt, der Hotel Knowledge Assistant, gewann die Hackshow des Jahrgangs: erster Platz unter allen Teams",
          ],
        },
        {
          title: "AWS Cloud Practitioner Essentials",
          issuer: "AWS Training & Certification",
          date: "August 2025",
          image: "/Screenshot 2026-03-10 at 01.00.39.png",
          facts: [
            "Zentrale AWS-Services und ihr Zusammenspiel",
            "IAM, Sicherheitspraktiken, das Modell der geteilten Verantwortung",
            "Preise, Abrechnung und Strategien zur Kostenoptimierung",
            "EC2, S3, RDS und Lambda in der Praxis",
            "Die globale AWS-Infrastruktur: Regionen, Availability Zones, Edge-Standorte",
          ],
        },
      ],
    },
    skills: {
      label: "Der Werkzeugkasten",
      title: "Womit ich arbeite",
      groups: [
        { name: "Cloud & Infrastruktur", items: "Azure, AWS, Terraform, Azure AKS, Azure AI Foundry, Blob Storage, Azure AI Search" },
        { name: "Container & Orchestrierung", items: "Docker, Kubernetes, Docker Compose, Helm" },
        { name: "CI/CD & Automatisierung", items: "GitHub Actions, Git, Ansible" },
        { name: "Monitoring & Observability", items: "Prometheus, Grafana, Alerting" },
        { name: "Entwicklung", items: "Python, Node.js, FastAPI, Next.js, Swift, Bash" },
        { name: "Datenbanken & Caching", items: "MongoDB, Redis, PostgreSQL" },
      ],
    },
    contact: {
      label: "Kontakt",
      title: "Die Rezeption ist besetzt",
      sub: "Ich suche DevOps- und Cloud-Engineering-Stellen in Deutschland. Wenn Ihre Systeme laufen müssen, sollten wir sprechen.",
      emailLabel: "E-Mail",
      copied: "Kopiert",
      copyHint: "Klicken zum Kopieren",
    },
    footer: { location: "Fotios Pongas · Deutschland" },
  },
};

export const links = {
  email: "hello@fotiospongas.dev",
  github: "https://github.com/Kabamaru2372",
  linkedin: "https://www.linkedin.com/in/f-pongas-devops-cloud/",
  cv: "/Fotios_Pongas_CV.pdf",
};

export const picksyShots = ["/picksy-new-1.jpg", "/picksy-new-2.jpg", "/picksy-new-3.jpg"];
export const hackshowPhoto = "/IMG_2589.jpeg";
